questions = [
#["Question", ["A", "b", "c", "d"], "c"],
["What is 2 + 2?", ["apple", "3.333", "4", "something else"], "4"],
["How many notes are in a musical major scale?", ["7","8","12","14"], "7"],
["What part of speech is the word \"dog\"? ", ["verb", "adjective", "preposition", "noun"], "noun"],
["What is the 7th planet from the sun?", ["Mercury", "Neptune", "Jupiter", "Earth"], "Neptune"],
["What color do red and blue make when mixed?", ["Green", "Yellow", "Purple", "Brown"], "Purple"],
["In what year was the declaration of independence signed?", ["2112", "1892", "1777", "1776"], "1776"],
["What is the tenth digit of pi?", ["3", "1", "4", "6"], "3"],
["How many wives did King Henry VIII have?", ["0", "6", "1", "23"], "6"],
["What is the periodic table symbol for the element potassium?", ["Pt", "P", "Pm", "K"], "K"],
["What is the name of the main character and narrator of Moby Dick?", ["Ishmael", "Ahab", "Queequeg", "Sherlock"], "Ishmael"],
["What is the unit of measurement for spiciness?", ["Kelvin", "Scoville", "Burners", "Melville"], "Scoville"],
["How many tiles are in a sudoku puzzle?", ["15", "33", "27", "81"], "81"],
["What is the smallest prime number?", ["1", "2", "3", "4"], "2"],
["What is one-third of 60?", ["10", "20", "30", "40"], "20"],
["How many vowels are present in the English alphabet?", ["2", "4", "5", "7"], "5"],
["What is the fifth letter of the English alphabet?", ["D", "E", "F", "G"], "E"],
["How many sides are present in a hexagon?", ["4", "6", "8", "10"], "6"],
["How many numbers should be added to 85 to make it 100?", ["12", "15", "17", "25"], "15"],
["How many degrees are there in a circle?", ["250", "300", "360", "400"], "360"],
["What is a triangle with 3 unequal sides called?", ["Acute", "Obtuse", "Scalene", "Equilateral"], "Scalene"],
["Red and yellow mixed together creates what color?", ["Blue", "Violet", "Green", "Orange"], "Orange"],
["How many muscles are there in the human body?", ["212", "350", "555", "640"], "640"],
["Which planet is the hottest in our Solar System?", ["Mars", "Venus", "Saturn", "Jupiter"], "Venus"],
["Which is the most abundant gas in our atmosphere?", ["Nitrogen", "Hydrogen", "Sodium", "Oxygen"], "Nitrogen"],
["When exposed to acid, what color does litmus paper turn?", ["Blue", "Red", "White", "Black"], "Red"],
["Which planet is the closest to the Sun?", ["Mercury", "Venus", "Earth", "Mars"], "Mercury"],
["Which fish is known for not having any brain or heart?", ["Shark", "Salmon", "Jellyfish", "Trout"], "Jellyfish"],
["What is the slowest living mammal on earth?", ["Koala", "Sloth", "Turtle", "Giraffe"], "Sloth"],
["I am a part of a plant that makes food for the plant. What am I?", ["Leaves", "Stem", "Roots", "Soil"], "Leaves"],
["Bees are responsible to make which edible substance?", ["Butter", "Honey", "Chocolate", "Bread"], "Honey"],
["What was the color of Mickey Mouse shorts?", ["Black", "Yellow", "Red", "White"], "Red"],
["What is the name of our solar system?", ["Milky Way", "Andromeda", "Triangulum", "Alcyoneus"], "Milky Way"],
["Which planet has the most Moons?", ["Mars", "Uranus", "Saturn", "Jupiter"], "Jupiter"],
["Which sea separates Europe and Africa?", ["Red", "Black", "Mediterranean", "Atlantic"], "Mediterranean"],
["Which Ocean is located on the west coast of North America?", ["Oceanic", "Pacific", "Atlantic", "Australian"], "Pacific"],
["What is the capital of Japan?", ["Tokyo", "Kyoto", "Kobe", "Osaka"], "Tokyo"],
["Where is Buckingham Palace located?", ["New York", "London", "Moscow", "Sydney"], "London"],
["Which continent contains the most countries?", ["America", "Asia", "Africa", "Europe"], "Africa"],
["Which continent is the largest in area?", ["America", "Asia", "Africa", "Europe"], "Asia"],
["Which desert mostly covers North Africa?", ["Gobi", "Mojave", "Kalahari", "Sahara"], "Sahara"],
["Which is the largest rainforest in the world?", ["Amazon", "Congo", "Valdivian", "Kinabalu"], "Amazon"],
["How many years are present in a century?", ["10", "50", "100", "1000"], "100"],
["How many years are present in a decade?", ["10", "20", "50", "100"], "10"],
["On which date is Halloween celebrated?", ["October 21st", "October 31st", "November 2nd", "November 10th"], "October 31st"],
["Where is the Eiffel Tower?", ["Paris", "Las Vegas", "Tokyo", "Cairo"], "Paris"],
["How many chambers are there in a human heart?", ["1", "2", "4", "6"], "4"],
["How many legs does a spider have?", ["4", "8", "10", "12"], "8"],
["Which land animal is the fastest?", ["Tiger", "Panther", "Cheetah", "Leopard"], "Cheetah"],
["What is the longest river in the world?", ["Nile", "Amazon", "Mississippi", "Yellow"], "Nile"],
["How many teeth do most adult humans have?", ["24", "30", "32", "40"], "32"],
["How many elements are in the periodic table?", ["100", "110", "118", "120"], "118"],
["How many bones does a worm have in their bodies?", ["0", "1", "10", "20"], "0"],
["What is the hardest natural substance in the world?", ["Sapphire", "Ruby", "Emerald", "Diamond"], "Diamond"],
["How many arms do most starfish have?", ["4", "5", "6", "7"], "5"],
["How many phases does the Moon have?", ["8", "10", "12", "14"], "8"],
["What is the tallest mountain in the world?", ["Everest", "K2", "Lhotse", "Makalu"], "Everest"],
["Where did the Olympic Games originate? ", ["Italy", "Russia", "Eygpt", "Greece"], "Greece"],
["What degree is a right angle??", ["45", "90", "180", "360"], "90"],
["How many colors are in a rainbow?", ["5", "6", "7", "8"], "7"],
["How much is a Bakers Dozen?", ["11", "12", "13", "14"], "13"],
["How many pints are in a gallon?", ["8", "10", "12", "14"], "8"],
["When was Jurassic Park Released?", ["1973","1983", "1993","2003"], "1993"],
["What is the brightest object in the Universe?", ["White Dwarf Stars", "Neutron Stars", "Quasars", "Gamma Ray Bursts"]]
]